name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint with Black
        run: |
          cd ..
          if [ "$RUNNER_OS" == "Windows" ]; then
            python.exe -m pip install black
            python.exe -m black nats_bench -l 120 --check --diff
            python.exe -m black tests -l 120 --check --diff
          else
            python --version
            echo $PWD
            python -m pip install black
            python -m black . -l 120 --check --diff
          fi
        shell: bash

      - name: Install nats_bench from source
        run: |
          python setup.py install

      - name: Run tests with pytest
        run: |
          export FAKE_TORCH_HOME="fake_torch_dir"
          python -m pytest . --durations=0
